version: '3'
services:
  asrserver:
    image: harbor.cowarobot.com/voyance/asr_server:20240228
    ports:
      - "40005:40005"
    runtime: runc
    restart: always
    user: root
    environment:
      - DISPLAY=unix$DISPLAY
      - GDK_SCALE
      - GDK_DPI_SCALE
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    privileged: true
    volumes:
      - ./code:/work/code
    deploy:
      resources:
        reservations:
          devices:
            - driver: ""
              count: all
              capabilities: [gpu]
              options: {}

